name: Test scuri code
pr:
    - master
    - release/*
trigger:
    - master
pool:
    vmImage: 'ubuntu-latest'

variables:
  - name: DISPLAY
    value: :99
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14

  - script: sudo apt-get install -y xvfb
    displayName: Install xvfb virtual display

  - script: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    displayName: start virtual display
  
  - script: npm ci
    displayName: Install dependencies

  - script: npm run test
    displayName: Test

  - script: npm run vscode:prepublish
    displayName: prepare for publish


